Ess_temp_project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('employee.urls'))
]

employee/urls.py
from django.urls import path
from . import views


app_name = "employee"


urlpatterns = [
    path('',views.userlogin,name='userlogin'),
    path('userlogout',views.userlogout,name="userlogout"),
    path('userdashboard/',views.userdashboard,name='userdashboard'),
    path('userdesignation/',views.userdesignation,name='userdesignation'),
    path('userdesignation_list/',views.userdesignation_list,name='userdesignation_list'),
    path('userdepartment/',views.userdepartment,name='userdepartment'),
    path('userdepartment_list/',views.userdepartment_list,name='userdepartment_list'),
    path('useremployee_form/',views.useremployee_form,name='useremployee_form'),
    path('useremployee_list/',views.useremployee_list,name='useremployee_list'),
    path('userleave_form/',views.userleave_form,name='userleave_form'),
    path('userleave_list/',views.userleave_list,name='userleave_list'),
    path('userleave_type/',views.userleave_type,name='userleave_type'),
    path('userleave_type_list/',views.userleave_type_list,name='userleave_type_list'),
    path('userpuch_in/',views.userpuch_in,name='userpuch_in'),
    path('userpuch_out/<id>',views.userpuch_out,name='userpuch_out'),
    path('user_attendence/',views.user_attendence,name='user_attendence'),
    path('userleave_delete/<int:id>',views.userleave_delete,name="userleave_delete"),
    path('approvrd_reject/<int:id>/<str:start_date>',views.approvrd_reject,name="approvrd_reject"), 

   
    

    
]

templates/designation folder/designation.html
{%extends 'base.html'%}
{%block content%}
<!-- 
{%for message in messages%}
<div class="alert alert-danger alert-dismissible fade show" role="alert"><button type="button" class="btn-close"
    data-bs-dismiss="alert"></button>
    {{message}}
</div>
{%endfor%} -->
</br>
<a href="{%url 'employee:userdesignation_list'%}" class="btn btn-primary" style="margin:0% 0% 0% 95%;">Back</a></br></br>

    <center>
        <h2 class="alert alert-info"><u>DESIGNATION FORM</u></h2>
    </center><br>
    <form method="post" action="/userdesignation/">
        {% csrf_token %}
        <div class="container col-5">
            <div class="row">
                <div class="mb-3 ">
                    <label for="name" class="form-label" style="color: rgb(18, 20, 22);"><b>Name:</b></label>
                    <input type="text" class="form-control" id="name" name="name" placeholder="Enter Your Designation">     
                </div>

            </div>


        <center> <button type="submit" class="btn btn-primary">Submit</button></center>
</div>

</form>

{%endblock%}

templates/designation folder/designation_list.html
{%extends 'base.html'%}
{%block content%}

<head>
  <style>
    table {
      font-family: arial, sans-serif; 
      border-collapse: collapse;
      width: 100%;
    }

    td,
    th {
      text-align: left;
      padding: 8px;
      color: rgb(1, 1, 14);
      font-size: larger;
    }

    .list {
      background-image: url('/static/image/dark2.webp');
      background-repeat: no-repeat;
      background-attachment: fixed;
      background-size: cover;
    }
    table, th, td {
  border: 1px solid white;        
  border-collapse: collapse;
}
th, td {
  background-color: #99cdf0;
}
  </style>
</head>

<body class="list">
</br>
<a href="{%url 'employee:userdesignation'%}" class="btn btn-primary" style="margin:0% 0% 0% 90%;">+Add Designation</a></br></br>

    <center>
        <h2 class="alert alert-danger"><u>DESIGNATION LIST</u></h2>
    </center><br>
    <div class="col-sm-4" style="margin-left:32.5%;">
  <table>
    <tr>
      <th>No.</th>
      <th>Name</th>
    </tr>
    {%for i in data%}
    <tr>
      <td>{{forloop.counter}}</td>
      <td>{{i.designation_name}}</td>
    </tr>
    {% endfor %}
  </table></div>
  <br />
</body>
{%endblock%}