Ess_temp_project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('employee.urls'))
]

employee/urls.py
from django.urls import path
from . import views


app_name = "employee"


urlpatterns = [
    path('',views.userlogin,name='userlogin'),
    path('userlogout',views.userlogout,name="userlogout"),
    path('userdashboard/',views.userdashboard,name='userdashboard'),
    path('userdesignation/',views.userdesignation,name='userdesignation'),
    path('userdesignation_list/',views.userdesignation_list,name='userdesignation_list'),
    path('userdepartment/',views.userdepartment,name='userdepartment'),
    path('userdepartment_list/',views.userdepartment_list,name='userdepartment_list'),
    path('useremployee_form/',views.useremployee_form,name='useremployee_form'),
    path('useremployee_list/',views.useremployee_list,name='useremployee_list'),
    path('userleave_form/',views.userleave_form,name='userleave_form'),
    path('userleave_list/',views.userleave_list,name='userleave_list'),
    path('userleave_type/',views.userleave_type,name='userleave_type'),
    path('userleave_type_list/',views.userleave_type_list,name='userleave_type_list'),
    path('userpuch_in/',views.userpuch_in,name='userpuch_in'),
    path('userpuch_out/<id>',views.userpuch_out,name='userpuch_out'),
    path('user_attendence/',views.user_attendence,name='user_attendence'),
    path('userleave_delete/<int:id>',views.userleave_delete,name="userleave_delete"),
    path('approvrd_reject/<int:id>/<str:start_date>',views.approvrd_reject,name="approvrd_reject"), 

   
    

    
]

templates/attendence.html
{%extends 'base.html'%}
{%block content%}



<head>
  <style>
    table {
      font-family: arial, sans-serif; 
      border-collapse: collapse;
      width: 100%;
    }

    td,
    th {
      text-align: left;
      padding: 8px;
      color: rgb(1, 1, 14);
      font-size: large;
    }

    .list {
      background-image: url('/static/image/dark2.webp');
      background-repeat: no-repeat;
      background-attachment: fixed;
      background-size: cover;
    }
    table, th, td {
  border: 1px solid white;        
  border-collapse: collapse;
}
th, td {
  background-color: #99cdf0;
}
  </style>
  </head>







    <body class="list">

    
        <center>
            <h2 class="alert alert-danger"><u>ATTENDENCE LIST</u></h2>
        </center><br>
      
<table>
    <tr>
      <th>Employee Name</th>
      <th>Date</th>
      <th>Puch in</th>
      <th>Puch out</th>
      <th>Duration Time</th>
  
    </tr>
    
    {%for punch_in_out_list in punch_in_out%}
    
    <tr>
      <td>{{punch_in_out_list.employee_name}}</td>
      <td>{{punch_in_out_list.date}}</td>
      <td>{{punch_in_out_list.punch_in}}</td>
      <td>{{punch_in_out_list.punch_out}}</td>
      <td>{{punch_in_out_list.duration}}</td>
    </tr>
    {% endfor %}
  </table>
</body>
{%endblock%}

templates/base.html
{%load static%}
<!DOCTYPE html>
<html>


<head>
  <title>ESS POROJECT</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs/dist/tf.min.js"> </script>
<style>
  .index {
      background-image: url('/static/image/200.jfif');
      background-repeat: no-repeat;
      background-attachment: fixed;
      background-size: cover;
    }

    .card { 
      background-image: url('/static/image/back.jpg');
      background-repeat: no-repeat;
      background-attachment: fixed;
      background-size: cover;
    }

    .Dashboard,
    .Designation {
      background-image: url('/static/image/tree.png');
      background-repeat: no-repeat;
      background-attachment: fixed;
      background-size: cover;
    }

</style>
</head>


<body>

  <nav class="navbar navbar-expand-sm navbar-dark bg-dark sticky-top">
    <div class="container-fluid">
      <a
        href="https://www.google.com/search?q=india&source=lmns&bih=969&biw=1920&hl=en&sa=X&ved=2ahUKEwj567Xv3938AhXHiNgFHXKUB04Q_AUoAHoECAEQAA">
        <img class="navbar-brand" src="/static/image/india.png" style="height: 50px; width: 50px; border-radius: 50%;"
          class="rounded-circle"></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mynavbar">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="mynavbar">
        <ul class="navbar-nav me-auto">
          

          <li class="nav-item">
            <a class="nav-link" href="{%url 'employee:userdashboard'%}">Dashboard</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{%url 'employee:userdesignation_list'%}">Designation</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{%url 'employee:userdepartment_list'%}">Department</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{%url 'employee:userleave_type_list'%}">Leave Type</a>
          </li>
          
          <li class="nav-item">
            <a class="nav-link" href="{%url 'employee:userleave_list'%}">Leave</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{%url 'employee:useremployee_list'%}">Employee</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{%url 'employee:user_attendence'%}">Attendence</a>
          </li> 
        </ul>

        
        <ul class="nav navbar-nav navbar-right">
          {%if request.user.is_authenticated%}
          <li><a class="nav-link" href="{%url 'employee:userlogout'%}"> LogOut</a></li>
          {%else%}
          <li><a class="nav-link" href="{%url 'employee:userlogin'%}">Login</a></li>
          {%endif%}
        </ul>
      </div>
    </div>
  </nav>


{%block content%}
{%endblock%}




</body>


</html>

templates/dashboard.html
{%extends 'base.html'%}
{%block content%}



<head>
    <style>
        b {
            font-family: arial, sans-serif;
            border-collapse: collapse;
            width: 100%;
            font-size: 200%;
            color: rgb(250, 100, 6);

        }

        table {
            font-family: arial, sans-serif;
            border-collapse: collapse;
            width: 100%;
        }

        td,
        th {
            text-align: left;
            padding: 8px;
            color: rgb(231, 231, 241);
        }

        .list {
            background-repeat: no-repeat;
            background-attachment: fixed;
            background-size: cover;
        }

        table,
        th,
        td {
            border: 1px solid;
            border-collapse: collapse;
        }

        th,
        td {
            background-color: #d49696;
        }


    </style>
</head>


<div class="">

    <body>

        {%if request.user.is_authenticated%}

        <br><br>
        <center><b>Welcome,
                {{request.user.employee_user.first_name}} {{request.user.employee_user.last_name}}</b></center>

        {%endif%}

        <br><br>
        {%if request.user.is_authenticated%}


        <div class="container" >
            <center>
                <ul>
                    <form method="post" action="/userpuch_in/">
                        {% csrf_token %}
                        <button type="submit" id="punchin" class="btn btn-primary" value="puchin" name="puchin" ><a>Punch-in</a></button>
                    </form>
                </ul>
            </center>
            <center>
                <ul>
                    <form method="post" action="/userpuch_out/{{attendance_ids}}">
                        {% csrf_token %}

                    <button type="submit" id="punchout" class="btn btn-primary" value="puchout" name="puchout">Punch-out</button>
                    </form>
                </ul>
            </center>
        </div>



        <br><br><br>
        <div class="col-sm-4" style="margin-left:35%;">
            <table class="table table-dark table-striped">
                <tr>
                    <th>Puch in</th>
                    <th>Puch out</th>

                </tr>
                {%for punch_in_out_time_list in p_in%}
                <tr>
                    <td>{{punch_in_out_time_list.punch_in}}</td>
                    <td>{{punch_in_out_time_list.punch_out}}</td>
                </tr>
                {% endfor %}
            </table>
        </div>  
        {%endif%}
        {{data}}


    </body>
</div>
{%endblock%}

templates/login.html
{%extends 'base.html'%}
{%block content%}

<marquee>{{msg}}</marquee>


<div class="login">
    <center>
        <h2 class="alert alert-info"><u>LOGIN FORM</u></h2>
    </center><br>
    <form action="{%url 'employee:userlogin'%}" method="post">
        {% csrf_token %}
        <div class="container col-5">
            <div  class="row">
        <div class="mb-3">
            <label for="exampleInputemail1" class="form-label"><b style="color: rgb(18, 20, 22)">Email:</b></label>
            <input type="text" class="form-control" id="username" name="username" placeholder="Enter Email">
        </div>
        <div class="mb-3">
            <label for="exampleInputPassword1" class="form-label"><b style="color: rgb(18, 20, 22)">password:</b></label>
            <input type="password" class="form-control" id="password" name="password" placeholder="Enter Password">
        </div>
        </br></br></div></div>
        <div class="d-grid gap-2">
            <center> <button type="submit" class="btn btn-primary">Login</button></center>
        </div>
    </form>

</br></br></br></br></br></br></br></br></br></br></br></br></br></br></br>

</div>

{%endblock%}